Repository shravan2524/hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#14 palindroam
  CPP/palindroam.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#18 reverse a number problem done
  CPP/reverse.cpp
Labels: hacktoberfest-accepted

#22 :sparkles: Add Bredth First Search
  CPP/bfs.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#21 :sparkles: Add Depth first search
  CPP/dfs.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#24 Added binary exponentiation
  CPP/binary_exponentiation.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#37 Added Z-Function in C++
  CPP/ZFunction.cpp
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
